### ISSUE TITLE
make error on Fedora9

### ISSUE THREAD

**Issue by ZhuChaozheng** [hmgle/h264_to_rtp#1]
when I download your project,and run make and make test on Fedora9 of VMware right now,but there are some errors and I can't kill it! The errors is like:
send:Bad file descriptor
----- send fail errno is 9----
send:Bad file descriptor
----- send fail errno is 9----
send:Bad file descriptor
----- send fail errno is 9----
and always repeat.Can you give me some tips?

**Comment by hmgle** [comment]
@ZhuChaozheng 运行前需要确定你安装了 ffplay 或者 vlc:

```
$ ffplay --version # 或 vlc --version
```

如果找不到命令需要在你的系统上安装其中的任何一个, 如果使用 vlc 需要替换 Makefile 里面的 ffplay 为 vlc

最后执行 make test 看看是否还是这样.

**Comment by ZhuChaozheng** [comment]
哈哈！原来你是中国人呀。。。害我英文打字累死了。。。我的ffmpeg安装的时候必须要到他的bin目录下才能运行ffplay，这怎么办呢？？

**Comment by hmgle** [comment]
yum install ffmpeg 试试, 如果安装后没有 ffplay, 可以修改 Makefile 使用 vlc. vlc 应该容易安装了.

**Comment by ZhuChaozheng** [comment]
[root@tom video_encode_V2.0]# yum install ffmpeg
Loaded plugins: refresh-packagekit
Setting up Install Process
Parsing package install arguments
No package ffmpeg available.
Nothing to do
好像我的资源里没有ffmpeg，不能直接下载安装，我已经将ffmpeg的源码下载过了并且编译安装了，可是就是无法直接输入ffplay执行命令，我估计是什么环境变量的没有搞。。。

**Comment by hmgle** [comment]
@ZhuChaozheng 修改下 Makefile 让 ffplay 包含路径就可以了, 或者把 ffplay 添加到 PATH.
